// server.js
const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const QR = require("./QR");
const directive = require("./Directives");
const Admin = require("./Admin");
const Food_items = require("./fooditems");
const meneu = require("./FoodMeneue");
const logs = require("./logs");
const user = require("./UserModel");
const portfolio = require("./portfolio");
const WeatherLog = require("./WeatherLog");

require("dotenv").config();

// Prefer IPv4 across Node DNS (avoids IPv6 egress issues on some PaaS like Railway)
const dns = require("dns");
if (dns.setDefaultResultOrder) {
  dns.setDefaultResultOrder("ipv4first");
}

const bcrypt = require("bcrypt");
const saltRounds = 11;
const validator = require("validator");

// -----------------------------------------------------------------------------
// APP
const app = express();
app.use(cors());
app.set("trust proxy", true);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// -----------------------------------------------------------------------------
// QR storage
app.post("/store-qr", async (req, res) => {
  try {
    const { orderId, mess, date, dish } = req.body;
    const newQR = new QR({ orderId, mess, date, dish });
    await newQR.save();
    res.json({ message: "QR data saved successfully" });
  } catch (error) {
    console.error("Failed to save QR data:", error);
    res.status(500).json({ error: "Failed to save QR data" });
  }
});

// -----------------------------------------------------------------------------
// Admin login (unchanged)
app.post("/login", async (req, res) => {
  const { username, password } = req.body;
  const found = await Admin.findOne({ username });
  if (found) {
    if (password === found.password) {
      res.json({ message: "Login successful", user: found });
    } else {
      res.status(401).json({ message: "Invalid password" });
    }
  } else {
    res.status(404).json({ message: "User not found" });
  }
});

// -----------------------------------------------------------------------------
const FeedbackModel = require("./FeedbackModel");

// feedback submit
app.post("/submit-feedback", async (req, res) => {
  const { orderId, mess, date, rating, comment } = req.body;
  try {
    const qrExists = await QR.findOne({ orderId });
    if (!qrExists) {
      return res.status(400).json({
        error: "Invalid QR code. This order was not generated by admin.",
      });
    }
    const feedback = new FeedbackModel({
      orderId,
      mess,
      date,
      rating,
      comment,
    });
    await feedback.save();
    res.status(200).json({ message: "Feedback submitted successfully." });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(399).json({
        error: "Feedback has already been submitted for this order.",
      });
    }
    console.error("Unexpected error while submitting feedback:", err);
    res.status(500).json({
      error: "An unexpected error occurred while submitting feedback.",
    });
  }
});

// -----------------------------------------------------------------------------
// feedback summary
app.get("/feedback-summary", async (req, res) => {
  const { mess } = req.query;
  if (!mess) return res.status(400).json({ error: "Mess name is required." });
  try {
    const totalOrders = await QR.countDocuments({ mess });
    const feedbacksReceived = await FeedbackModel.countDocuments({ mess });
    res.json({ totalOrders, feedbacksReceived });
  } catch (err) {
    console.error("Error in /feedback-summary:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// -----------------------------------------------------------------------------
// analytics
app.get("/analytics", async (req, res) => {
  const { mess } = req.query;
  if (!mess) return res.status(400).json({ error: "Mess name is required." });

  try {
    const feedbacks = await FeedbackModel.find({ mess });
    let total = 0;
    let one = 0,
      two = 0,
      three = 0,
      four = 0,
      five = 0;

    for (let i = 0; i < feedbacks.length; i++) {
      const r = parseInt(feedbacks[i].rating, 10);
      if (r === 1) {
        one++;
        total += 1;
      } else if (r === 2) {
        two++;
        total += 2;
      } else if (r === 3) {
        three++;
        total += 3;
      } else if (r === 4) {
        four++;
        total += 4;
      } else if (r === 5) {
        five++;
        total += 5;
      }
    }

    const averageRating =
      feedbacks.length === 0 ? 0 : (total / feedbacks.length).toFixed(2);
    res.json({
      averageRating,
      ratingCounts: { 1: one, 2: two, 3: three, 4: four, 5: five },
    });
  } catch (err) {
    console.error("Error in /analytics:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// -----------------------------------------------------------------------------
// directives
app.get("/directive", async (req, res) => {
  try {
    const alldr = await directive.find();
    if (alldr.length === 0) {
      res.status(204).json("No directives yet.");
    } else {
      res.status(200).json(alldr);
    }
  } catch (err) {
    console.error("Error fetching directives:", err);
    return res.status(500).json("Internal server error");
  }
});

// -----------------------------------------------------------------------------
// top feedback
app.get("/top-feedbacks", async (req, res) => {
  const mess = req.query.mess;
  if (!mess) return res.status(400).json({ message: "Mess is required" });
  try {
    const topComments = await FeedbackModel.find({
      mess,
      comment: { $ne: "" },
    }).limit(12);
    res.json(topComments);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Server error" });
  }
});

// -----------------------------------------------------------------------------
// MENU - HASSAN
app.get("/api/fooditems", async (req, res) => {
  try {
    const items = await Food_items.find();
    res.json(items);
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, message: error.message });
  }
});

app.put("/api/menu", async (req, res) => {
  const { mess, date, breakfast, lunch, Dinner } = req.body;

  try {
    const updatedMenu = await meneu.findOneAndUpdate(
      { mess, date },
      { mess, date, breakfast, lunch, Dinner },
      { new: true, upsert: true, setDefaultsOnInsert: true }
    );
    res.status(200).json({ success: true, data: updatedMenu });
  } catch (error) {
    console.error("❌ Error saving menu:", error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// -----------------------------------------------------------------------------
// Student page routes
app.get("/api/student-menu", async (req, res) => {
  const { mess } = req.query;
  if (!mess) return res.status(400).json({ error: "Mess name is required." });

  const today = new Date()
    .toLocaleDateString("en-GB", {
      timeZone: "Asia/Karachi",
      day: "2-digit",
      month: "long",
      year: "numeric",
    })
    .replace(/ /g, "-");

  try {
    const menu = await meneu.findOne({ mess, date: today });
    if (!menu)
      return res.status(204).json({ message: "No menu found for today." });
    res.status(200).json(menu);
  } catch (err) {
    console.error("Error fetching today's menu:", err);
    res.status(500).json({ error: "Internal server error." });
  }
});

// -----------------------------------------------------------------------------
// STUDENT AUTH (Signup + Login)

// SIGNUP (creates user with verify:false and sends verification email)
app.post("/signupstd", async (req, res) => {
  const { name, email, password, pass2 } = req.body;
  const allowedDomain = "@cuiatd.edu.pk";

  const normalizedEmail = (email || "").toLowerCase();

  if (
    validator.isEmpty(name || "") ||
    validator.isEmpty(normalizedEmail || "") ||
    validator.isEmpty(password || "") ||
    !validator.isLength(password || "", { min: 8 }) ||
    validator.isEmpty(pass2 || "") ||
    password !== pass2 ||
    !validator.isEmail(normalizedEmail || "")
    // || !normalizedEmail.endsWith(allowedDomain)
  ) {
    return res.status(403).json({
      status: "Denied",
      message: `Invalid Input or email not from ${allowedDomain} domain`,
    });
  }

  try {
    const exists = await user.findOne({ email: normalizedEmail });
    if (exists) return res.status(400).json("User already exists.");

    const hashedPassword = await bcrypt.hash(password, saltRounds);
    const newUser = new user({
      name,
      email: normalizedEmail,
      password: hashedPassword,
    }); // verify defaults to false
    await newUser.save();

    // Send verification email
    try {
      const base = process.env.BASE_URL || "http://localhost:5000";
      const verifyLink = `${base}/verify/${newUser._id}`;
      await app.locals.mailer.sendVerificationMail({
        to: normalizedEmail,
        name,
        link: verifyLink,
        fromName: "Zayeeka Auth System",
      });
      console.log("Verification email sent to:", normalizedEmail);
    } catch (mailErr) {
      console.error("Email send failed:", mailErr);
    }

    try {
      await logs.create({
        ip: req.ip,
        userAgent: req.get("User-Agent"),
        endpoint: email,
        locationHint: "Unknown",
      });
    } catch (logErr) {
      console.error("SignUp logging failed:", logErr);
    }

    res
      .status(201)
      .json("Signup successful. Please check your email to verify.");
  } catch (err) {
    console.error("Signup error:", err);
    res.status(500).json({ message: "Server Error" });
  }
});

// LOGIN (blocks unverified users)
app.post("/loginstd", async (req, res) => {
  let { email, pass } = req.body;
  email = (email || "").toLowerCase();

  if (
    validator.isEmpty(email || "") ||
    validator.isEmpty(pass || "") ||
    !validator.isEmail(email || "")
  ) {
    return res.status(403).json({
      status: "Denied",
      message: "Invalid Input",
    });
  }

  try {
    const found = await user.findOne({ email });
    if (!found) return res.status(422).json("User Not Found");

    if (!found.verify) {
      return res.status(406).json("Please verify your email first.");
    }

    const isMatch = await bcrypt.compare(pass, found.password);
    if (!isMatch) return res.status(401).json("Incorrect Password");

    return res.status(201).json({ Status: "Access Granted", User: found.name });
  } catch (err) {
    console.error("Login error:", err);
    res.status(500).json({ message: "Server Error" });
  }
});

// -----------------------------------------------------------------------------
// OTHER
app.get("/api/mess", async (req, res) => {
  try {
    const names = await Admin.find({}, { name: 1, _id: 0 });
    res.json(names);
  } catch (err) {
    console.error("Failed to fetch admin names:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// -----------------------------------------------------------------------------
// EMAIL + VERIFICATION SECTION (Gmail SMTP via Nodemailer ONLY)
const nodemailer = require("nodemailer");

if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
  throw new Error(
    "SMTP_USER/SMTP_PASS are missing. Set your Gmail address and 16-char App Password."
  );
}

const FROM_NAME = process.env.FROM_NAME || "Portfolio";
const ADMIN_TO = process.env.ADMIN_TO || process.env.SMTP_USER;

// SINGLETON transporter — IMPORTANT: use hostname, prefer IPv4, STARTTLS
const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com", // hostname (cert matches this)
  port: 465,
  secure: true, // STARTTLS
  requireTLS: true,
  family: 4, // prefer IPv4 (Railway friendly)
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS, // Gmail App Password
  },
  pool: true,
  maxConnections: 3,
  maxMessages: 100,
  connectionTimeout: 15000,
  greetingTimeout: 15000,
  socketTimeout: 30000,
});

// Optional: verify SMTP connectivity at boot (shows in logs)
transporter.verify((err) => {
  if (err) {
    console.error("SMTP verify failed:", err?.response || err?.message || err);
  } else {
    console.log("SMTP ready to send");
  }
});

// Central mailer used by routes above
app.locals.mailer = {
  async send({ to, subject, html, replyTo, fromName = FROM_NAME }) {
    const mailOptions = {
      from: `"${fromName}" <${process.env.SMTP_USER}>`,
      to, // string or array
      subject,
      html,
      ...(replyTo ? { replyTo } : {}),
    };

    try {
      const info = await transporter.sendMail(mailOptions);
      console.log("SMTP send OK:", info && info.messageId);
      return info;
    } catch (e) {
      console.error("SMTP send FAIL:", e && (e.response || e.message || e));
      throw e;
    }
  },

  async sendVerificationMail({ to, name, link, fromName = FROM_NAME }) {
    const html = `
  <div style="font-family:Arial, sans-serif; max-width:600px; margin:0 auto; padding:20px; background-color:#f9f9f9; border-radius:8px; color:#333;">
    <h2 style="color:#0b5ed7;">Welcome to Zayeeka</h2>
    <p>Hi ${name},</p>
    <p>Thank you for signing up! You're just one step away from activating your account.</p>
    <p>Please click the button below to verify your email:</p>
    <p style="text-align:center;">
      <a href="${link}" style="background:#0b5ed7; color:#fff; padding:12px 20px; border-radius:6px; text-decoration:none; display:inline-block; font-weight:bold;">
        Verify My Email
      </a>
    </p>
    <p>If the button doesn't work, copy and paste this link into your browser:</p>
    <p style="word-break:break-all;"><code>${link}</code></p>
    <hr style="margin:30px 0; border:none; border-top:1px solid #ddd;" />
    <p style="font-size:13px; color:#777; margin-top:20px; line-height:1.5;">
      This is a system-generated email. Please do not reply directly.<br/>
      <strong>Disclaimer:</strong> Zayeeka is an independent student project and is not affiliated with, endorsed by, or accountable to COMSATS University Abbottabad in any official capacity.
    </p>
    <p style="margin-top:30px;">Best regards,<br><strong>Zayeeka Team</strong></p>
  </div>
`;
    return await this.send({
      to,
      subject: "Verify your email",
      html,
      fromName,
    });
  },
};

// -----------------------------------------------------------------------------
// VERIFY PAGES
app.get("/verify/:userId", async (req, res) => {
  const { userId } = req.params;
  const u = await user.findById(userId).lean();
  if (!u) return res.status(404).send("User not found");
  if (u.verify)
    return res.send("Your email is already verified. You can log in.");

  res.setHeader("Content-Type", "text/html");
  res.send(`
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>Verify Your Email | Zayeeka</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <style>
        body { font-family: Arial, sans-serif; background-color: #f7f7f7; color: #333; max-width: 420px; margin: 60px auto; padding: 30px; border-radius: 8px; box-shadow: 0 4px 16px rgba(0,0,0,0.1); background: #ffffff; }
        h2 { color: #0b5ed7; }
        input[type="password"] { width: 100%; padding: 10px; margin: 12px 0 20px 0; border: 1px solid #ccc; border-radius: 4px; font-size: 14px; }
        button { background-color: #0b5ed7; color: white; padding: 10px 16px; border: none; border-radius: 4px; font-size: 14px; cursor: pointer; }
        button:hover { background-color: #094bbf; }
        .note { font-size: 13px; color: #777; margin-top: 30px; }
      </style>
    </head>
    <body>
      <h2>Email Verification</h2>
      <p>To verify your email address <strong>${u.email}</strong>, please confirm your password below.</p>
      <form method="POST" action="/verify/${userId}">
        <label for="password">Confirm Password</label>
        <input name="password" id="password" type="password" required placeholder="Enter the password you chose during signup" />
        <button type="submit">Verify My Email</button>
      </form>
      <p class="note">
        This is <strong>not</strong> your institutional email password — it’s the password you created when registering your Zaayeka account.
      </p>
    </body>
  </html>
`);
});

app.post("/verify/:userId", async (req, res) => {
  const { userId } = req.params;
  const { password } = req.body;

  try {
    const u = await user.findById(userId);
    if (!u) return res.status(404).send("User not found");
    if (u.verify) return res.send("Already verified. You can log in.");

    const match = await bcrypt.compare(password, u.password);
    if (!match) return res.status(401).send("Incorrect password");

    u.verify = true;
    await u.save();

    res.send("Email verified successfully. You can now log in. Regards,");
  } catch (err) {
    console.error("Verify error:", err);
    res.status(500).send("Something went wrong");
  }
});

// -----------------------------------------------------------------------------
// portfolio route — send 2 emails (admin + user). Each has its own try/catch.
app.post("/portfolio", async (req, res) => {
  try {
    const { name, email, message } = req.body;

    // Validate inputs
    if (
      validator.isEmpty(name || "") ||
      validator.isEmpty(email || "") ||
      validator.isEmpty(message || "")
    ) {
      return res
        .status(400)
        .json({ error: "Name, email, and message are required." });
    }
    if (!validator.isEmail(email || "")) {
      return res.status(400).json({ error: "Invalid email format." });
    }

    // Save to database
    const newMessage = new portfolio({
      name: name.trim(),
      email: email.trim().toLowerCase(),
      message: message.trim(),
      ip: req.ip,
      userAgent: req.get("User-Agent"),
    });
    await newMessage.save();

    // Admin notification
    const adminHtml = `
  <div style="font-family: Arial, Helvetica, sans-serif; max-width: 640px; margin: 0 auto; background:#ffffff; border:1px solid #e5e7eb; border-radius:8px; overflow:hidden;">
    <div style="background:#0b5ed7; color:#ffffff; padding:12px 18px; font-weight:600; font-size:16px;">
      Portfolio Website — New Contact Submission
    </div>
    <div style="padding:20px 18px;">
      <p style="margin:0 0 14px 0; font-size:14px; color:#334155;">
        A new message was submitted via the contact form. Details are below.
      </p>
      <table style="width:100%; border-collapse:collapse; margin:10px 0 6px 0;">
        <tr><td style="width:160px; padding:8px 10px; font-weight:600; color:#111827; background:#f8fafc; border:1px solid #e5e7eb;">Name</td><td style="padding:8px 10px; color:#111827; border:1px solid #e5e7eb;">${name}</td></tr>
        <tr><td style="width:160px; padding:8px 10px; font-weight:600; color:#111827; background:#f8fafc; border:1px solid #e5e7eb;">Email</td><td style="padding:8px 10px; color:#111827; border:1px solid #e5e7eb;">${email}</td></tr>
      </table>
      <div style="margin-top:14px;">
        <div style="font-weight:600; color:#111827; margin-bottom:6px; font-size:13px;">Message</div>
        <div style="padding:12px; background:#ffffff; border:1px solid #e5e7eb; border-radius:6px; font-size:14px; color:#374151;">
          <pre style="margin:0; white-space:pre-wrap; word-wrap:break-word; font-family:inherit; line-height:1.55;">${message}</pre>
        </div>
      </div>
      <div style="margin-top:18px;">
        <div style="font-weight:600; color:#0b5ed7; margin-bottom:8px; font-size:13px;">Submission Metadata</div>
        <table style="width:100%; border-collapse:collapse;">
          <tr><td style="width:160px; padding:8px 10px; background:#f8fafc; font-weight:600; color:#111827; border:1px solid #e5e7eb;">IP Address</td><td style="padding:8px 10px; color:#111827; border:1px solid #e5e7eb;">${
            req.ip
          }</td></tr>
          <tr><td style="width:160px; padding:8px 10px; background:#f8fafc; font-weight:600; color:#111827; border:1px solid #e5e7eb;">Browser</td><td style="padding:8px 10px; color:#111827; border:1px solid #e5e7eb;">${req.get(
            "User-Agent"
          )}</td></tr>
          <tr><td style="width:160px; padding:8px 10px; background:#f8fafc; font-weight:600; color:#111827; border:1px solid #e5e7eb;">Timestamp</td><td style="padding:8px 10px; color:#111827; border:1px solid #e5e7eb;">${new Date().toLocaleString()}</td></tr>
        </table>
      </div>
    </div>
    <div style="padding:10px 16px; background:#fafbfc; border-top:1px solid #e5e7eb; text-align:center; font-size:12px; color:#667085;">
      This is a system-generated notification from your portfolio website.
    </div>
  </div>
`;

    const userHtml = `
        <div style="background:#f5f7fb; padding:24px;">
          <div style="max-width:640px; margin:0 auto; background:#ffffff; border:1px solid #e6e8f0; border-radius:8px; overflow:hidden; font-family:Arial, Helvetica, sans-serif;">
            <div style="background:#0b5ed7; color:#ffffff; padding:14px 20px; font-weight:600; font-size:16px;">
              Mubashir Shahzaib — Portfolio
            </div>
            <div style="padding:22px 20px;">
              <h2 style="margin:0 0 10px 0; color:#0b5ed7; font-size:20px; font-weight:700;">
                Your message has been received
              </h2>
              <p style="margin:0 0 12px 0; font-size:15px; color:#333333;">Hi ${name},</p>
              <p style="margin:0 0 12px 0; font-size:15px; color:#333333;">
                Thank you for reaching out via my portfolio website. I’ve received your message and appreciate you taking the time to connect.
              </p>
              <p style="margin:0 0 16px 0; font-size:15px; color:#333333;">
                I review every submission personally. If your inquiry requires a response, I’ll get back to you at <strong>${email}</strong>.
              </p>
              <div style="margin:18px 0; padding:12px 14px; background:#f8fafc; border:1px solid #e6e8f0; border-left:4px solid #0b5ed7; border-radius:6px; font-size:14px; color:#374151;">
                <div><strong>Submitted:</strong> ${new Date().toLocaleString()}</div>
              </div>
              <div style="margin-top:14px;">
                <div style="font-weight:600; color:#111827; margin-bottom:8px; font-size:14px;">Your message</div>
                <div style="padding:12px; background:#ffffff; border:1px solid #e5e7eb; border-radius:6px; font-size:14px; color:#374151;">
                  <pre style="margin:0; white-space:pre-wrap; font-family:inherit; line-height:1.5;">${message}</pre>
                </div>
              </div>
            </div>
            <div style="padding:12px 20px; background:#fafbfc; border-top:1px solid #e6e8f0; font-size:12px; color:#667085; text-align:center;">
              This is a system-generated confirmation from Mubashir Shahzaib’s portfolio contact form. Please do not reply to this email.
            </div>
          </div>
        </div>
      `;

    // Send emails (admin + user) with separate try/catch
    try {
      console.log("Admin notification target:", ADMIN_TO);
      await app.locals.mailer.send({
        to: ADMIN_TO,
        subject: "New Contact Form Submission - Portfolio Website",
        html: adminHtml,
        fromName: FROM_NAME,
        replyTo: email,
      });
      console.log("✅ Admin notification sent to:", ADMIN_TO);
    } catch (e) {
      console.error(
        "❌ Admin notification failed:",
        e?.response || e?.message || e
      );
    }

    try {
      await app.locals.mailer.send({
        to: email,
        subject: "Confirmation: Your message has been received",
        html: userHtml,
        replyTo: ADMIN_TO,
        fromName: FROM_NAME,
      });
      console.log("✅ User confirmation sent to:", email);
    } catch (e) {
      console.error(
        "❌ User confirmation failed:",
        e?.response || e?.message || e
      );
    }

    return res.status(200).json({
      message:
        "Message saved. Notification and confirmation emails attempted (check logs).",
    });
  } catch (err) {
    console.error("Error in /portfolio:", err);
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// -----------------------------------------------------------------------------
// Health endpoints (handy in prod)
app.get("/health", (req, res) => res.status(200).send("OK"));
app.get("/health/smtp", async (req, res) => {
  try {
    await transporter.verify();
    res.status(200).send("OK");
  } catch (e) {
    res.status(503).send(`SMTP not ready: ${e?.message || e}`);
  }
});

// -----------------------------------------------------------------------------
// log weather visit
app.post("/weather", async (req, res) => {
  try {
    const { city, country, coords } = req.body || {};

    const doc = {
      city: city ?? null,
      country: country ?? null,
      ip: req.ip,
      userAgent: req.get("User-Agent") || null,
    };

    if (coords && coords.lat != null && coords.lon != null) {
      const lat = Number(coords.lat);
      const lon = Number(coords.lon);
      if (Number.isFinite(lat) && Number.isFinite(lon)) {
        doc.coords = { lat, lon };
        doc.location = { type: "Point", coordinates: [lon, lat] };
      }
    }

    const saved = await WeatherLog.create(doc);
    res.status(201).json({ message: "Location logged", id: saved._id });
  } catch (err) {
    console.error("Error in /weather:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// -----------------------------------------------------------------------------
// BOOT
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
