const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const QR = require("./QR");
const directive = require("./Directives");
const Admin = require("./Admin");
const Food_items = require("./fooditems");
const meneu = require("./FoodMeneue");
const logs = require("./logs");
const user = require("./UserModel");
require("dotenv").config();

//---
const bcrypt = require("bcrypt");
const saltRounds = 11;
const validator = require("validator");
// -------------------------------------------------------------------------------

const app = express();
app.use(cors());
app.use(express.json());

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// -------------------------------------------------------------------------------

app.post("/store-qr", async (req, res) => {
  try {
    const { orderId, mess, date, dish } = req.body;

    const newQR = new QR({ orderId, mess, date, dish });
    await newQR.save();

    res.json({ message: "QR data saved successfully" });
  } catch (error) {
    res.status(500).json({ error: "Failed to save QR data" });
  }
});

// -------------------------------------------------------------------------------

app.post("/login", async (req, res) => {
  const { username, password } = req.body;

  const user = await Admin.findOne({ username });

  if (user) {
    if (password === user.password) {
      res.json({ message: "Login successful", user });
    } else {
      res.status(401).json({ message: "Invalid password" });
    }
  } else {
    res.status(404).json({ message: "User not found" });
  }
});
// -------------------------------------------------------------------------------

const FeedbackModel = require("./FeedbackModel");

app.post("/submit-feedback", async (req, res) => {
  const { orderId, mess, date, rating, comment } = req.body;

  try {
    const qrExists = await QR.findOne({ orderId });
    if (!qrExists) {
      return res.status(400).json({
        error: "Invalid QR code. This order was not generated by admin.",
      });
    }

    const feedback = new FeedbackModel({
      orderId,
      mess,
      date,
      rating,
      comment,
    });

    await feedback.save(); // 100 if feedback already submitted.

    res.status(200).json({ message: "Feedback submitted successfully." });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(399).json({
        error: "Feedback has already been submitted for this order.",
      });
    }

    console.error("Unexpected error while submitting feedback:", err);
    res.status(500).json({
      error: "An unexpected error occurred while submitting feedback.",
    });
  }
});

// -------------------------------------------------------------------------------
// total orders and feedbacks
app.get("/feedback-summary", async (req, res) => {
  const { mess } = req.query;

  if (!mess) {
    return res.status(400).json({ error: "Mess name is required." });
  }

  try {
    const totalOrders = await QR.countDocuments({ mess });
    const feedbacksReceived = await FeedbackModel.countDocuments({ mess });

    res.json({ totalOrders, feedbacksReceived });
  } catch (err) {
    console.error("Error in /feedback-summary:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});
// -------------------------------------------------------------------------------
app.get("/analytics", async (req, res) => {
  const { mess } = req.query;

  if (!mess) {
    return res.status(400).json({ error: "Mess name is required." });
  }

  try {
    const feedbacks = await FeedbackModel.find({ mess });

    let total = 0;

    let one = 0;
    let two = 0;
    let three = 0;
    let four = 0;
    let five = 0;

    for (let i = 0; i < feedbacks.length; i++) {
      const rating = parseInt(feedbacks[i].rating);

      if (rating === 1) {
        one++;
        total += 1;
      } else if (rating === 2) {
        two++;
        total += 2;
      } else if (rating === 3) {
        three++;
        total += 3;
      } else if (rating === 4) {
        four++;
        total += 4;
      } else if (rating === 5) {
        five++;
        total += 5;
      }
    }

    const averageRating =
      feedbacks.length === 0 ? 0 : (total / feedbacks.length).toFixed(2);

    res.json({
      averageRating,
      ratingCounts: {
        1: one,
        2: two,
        3: three,
        4: four,
        5: five,
      },
    });
  } catch (err) {
    console.error("Error in /analytics:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});
// -------------------------------------------------------------------------------
app.get("/directive", async (req, res) => {
  try {
    const alldr = await directive.find();
    if (alldr.length === 0) {
      res.status(204).json("No directives yet.");
    } else {
      res.status(200).json(alldr);
    }
  } catch (err) {
    console.error("Error fetching directives:", err);
    return res.status(500).json("Internal server error");
  }
});
// -------------------------------------------------------------------------------
app.get("/top-feedbacks", async (req, res) => {
  const mess = req.query.mess;

  if (!mess) return res.status(400).json({ message: "Mess is required" });

  try {
    const topComments = await FeedbackModel.find({
      mess,
      comment: { $ne: "" },
    }).limit(12);

    res.json(topComments);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Server error" });
  }
});
// -------------------------------------------------------------------------------
// MENU - HASSAN

// Routes

app.get("/api/fooditems", async (req, res) => {
  try {
    const items = await Food_items.find();
    res.json(items);
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, message: error.message });
  }
});

app.put("/api/menu", async (req, res) => {
  const { mess, date, breakfast, lunch, Dinner } = req.body;

  try {
    const updatedMenu = await meneu.findOneAndUpdate(
      { mess, date },
      {
        mess,
        date,
        breakfast,
        lunch,
        Dinner,
      },
      {
        new: true,
        upsert: true,
        setDefaultsOnInsert: true,
      }
    );

    res.status(200).json({ success: true, data: updatedMenu });
  } catch (error) {
    console.error("❌ Error saving menu:", error);
    res.status(500).json({ success: false, message: error.message });
  }
});

// -------------------------------------------------------------------------------
// Student page routes
app.get("/api/student-menu", async (req, res) => {
  const { mess } = req.query;

  if (!mess) {
    return res.status(400).json({ error: "Mess name is required." });
  }

  const today = new Date()
    .toLocaleDateString("en-GB", {
      timeZone: "Asia/Karachi",
      day: "2-digit",
      month: "long",
      year: "numeric",
    })
    .replace(/ /g, "-");

  try {
    const menu = await meneu.findOne({ mess, date: today });

    if (!menu) {
      return res.status(204).json({ message: "No menu found for today." });
    }

    res.status(200).json(menu);
  } catch (err) {
    console.error("Error fetching today's menu:", err);
    res.status(500).json({ error: "Internal server error." });
  }
});

// -------------------------------------------------------------------------------
app.post("/signupstd", async (req, res) => {
  const { name, email, password, pass2 } = req.body;

  const allowedDomain = "@cuiatd.edu.pk";

  if (
    validator.isEmpty(name) ||
    validator.isEmpty(email) ||
    validator.isEmpty(password) ||
    !validator.isLength(password, { min: 8 }) ||
    validator.isEmpty(pass2) ||
    password !== pass2 ||
    !validator.isEmail(email) ||
    !email.endsWith(allowedDomain)
  ) {
    return res.status(403).json({
      status: "Denied",
      message: `Invalid Input or email not from ${allowedDomain} domain`,
    });
  }

  try {
    const check = await user.findOne({ email });

    if (check) {
      return res.status(400).json("User already exists.");
    }

    const hashedPassword = await bcrypt.hash(password, saltRounds);

    const newUser = new user({ name, email, password: hashedPassword });
    await newUser.save();

    res.status(201).json("Operation Successful.");
  } catch (err) {
    res.status(500).json({ message: "Server Error" });
  }
});

//....
app.post("/loginstd", async (req, res) => {
  try {
    await logs.create({
      ip: req.ip,
      userAgent: req.get("User-Agent"),
      endpoint: "/api/login",
      locationHint: "Unknown",
    });
  } catch (logErr) {
    console.error("StudentView logging failed:", logErr);
  }
  const { email, pass } = req.body;

  if (
    validator.isEmpty(email) ||
    validator.isEmpty(pass) ||
    !validator.isEmail(email)
  ) {
    return res.status(403).json({
      status: "Denied",
      message: "Invalid Input",
    });
  }
  try {
    const check = await user.findOne({ email });

    if (check) {
      const isMatch = await bcrypt.compare(pass, check.password);

      if (isMatch) {
        return res
          .status(201)
          .json({ Status: "Access Granted", User: check.name });
      } else {
        return res.status(401).json("Incorrect Password");
      }
    } else {
      return res.status(422).json("User Not Found");
    }
  } catch (err) {
    res.status(500).json({ message: "Server Error" });
  }
});
// -------------------------------------------------------------------------------

app.get("/api/mess", async (req, res) => {
  try {
    const names = await Admin.find({}, { name: 1, _id: 0 });
    res.json(names);
  } catch (err) {
    console.error("Failed to fetch admin names:", err);
    res.status(500).json({ error: "Server error" });
  }
});

app.listen(5000, () => {
  console.log("Server is running on port 5000");
});
// -------------------------------------------------------------------------------
